version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nuxt_crm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: crm_db
    ports:
      - '5432:5432'
volumes:
  postgres_data: